--=========================================================================================================================
-- IconFontTextures
--==========================================================================================================================
INSERT OR REPLACE INTO IconFontTextures 
			(IconFontTexture,					IconFontTextureFile)
VALUES		('ICON_FONT_TEXTURE_EXTRA_PROMO',	'FontIcons_ExtraPromo'),
			('ICON_FONT_TEXTURE_PROMO_VP_00',	'FontIcons_promoVP_00'),
			('ICON_FONT_TEXTURE_PROMO_VP_01',	'FontIcons_promoVP_01'),
			('ICON_FONT_TEXTURE_PROMO_VP_02',	'FontIcons_promoVP_02'),
			('ICON_FONT_TEXTURE_PROMO_VP_03',	'FontIcons_promoVP_03'),
			('ICON_FONT_TEXTURE_PROMO_FANTASY',	'FontIcons_Scarlet'),
			('ICON_FONT_TEXTURE_TEMP_VPPI',		'FontIcons_tempVPPI'),
			('ICON_FONT_TEXTURE_CPM_TNL',		'FontIcons_CPM'),
			('ICON_FONT_TEXTURE_FIRESHIP_TNL',	'FontIcons_Fireship'),
			('ICON_FONT_TEXTURE_YFS_SEA',		'FontIcons_YfsSea');
--=========================================================================================================================
-- IconFontMapping
--==========================================================================================================================
INSERT OR REPLACE INTO IconFontMapping
			(IconName,								IconFontTexture,					IconMapping) 
VALUES		('ICON_PROMOTION_EXTRA_PROMO_01',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	1),
			('ICON_PROMOTION_EXTRA_PROMO_02',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	2),
			('ICON_PROMOTION_EXTRA_PROMO_03',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	3),
			('ICON_PROMOTION_EXTRA_PROMO_04',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	4),
			('ICON_PROMOTION_EXTRA_PROMO_05',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	5),
			('ICON_PROMOTION_EXTRA_PROMO_06',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	6),
			('ICON_PROMOTION_EXTRA_PROMO_07',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	7),
			('ICON_PROMOTION_EXTRA_PROMO_08',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	8),
			('ICON_PROMOTION_EXTRA_PROMO_09',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	9),
			('ICON_PROMOTION_EXTRA_PROMO_10',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	10),
			('ICON_PROMOTION_EXTRA_PROMO_11',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	11),
			('ICON_PROMOTION_EXTRA_PROMO_12',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	12),
			('ICON_PROMOTION_EXTRA_PROMO_13',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	13),
			('ICON_PROMOTION_EXTRA_PROMO_14',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	14),
			('ICON_PROMOTION_EXTRA_PROMO_15',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	15),
			('ICON_PROMOTION_EXTRA_PROMO_16',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	16),
			('ICON_PROMOTION_EXTRA_PROMO_17',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	17),
			('ICON_PROMOTION_EXTRA_PROMO_18',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	18),
			('ICON_PROMOTION_EXTRA_PROMO_19',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	19),
			('ICON_PROMOTION_EXTRA_PROMO_20',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	20),
			('ICON_PROMOTION_EXTRA_PROMO_21',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	21),
			('ICON_PROMOTION_EXTRA_PROMO_22',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	22),
			('ICON_PROMOTION_EXTRA_PROMO_23',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	23),
			('ICON_PROMOTION_EXTRA_PROMO_24',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	24),
			('ICON_PROMOTION_EXTRA_PROMO_25',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	25),
			('ICON_PROMOTION_EXTRA_PROMO_26',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	26),
			('ICON_PROMOTION_EXTRA_PROMO_27',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	27),
			('ICON_PROMOTION_EXTRA_PROMO_28',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	28),
			('ICON_PROMOTION_EXTRA_PROMO_29',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	29),
			('ICON_PROMOTION_EXTRA_PROMO_30',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	30),
			('ICON_PROMOTION_EXTRA_PROMO_31',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	31),
			('ICON_PROMOTION_EXTRA_PROMO_32',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	70),
			('ICON_PROMOTION_EXTRA_PROMO_33',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	33),
			('ICON_PROMOTION_EXTRA_PROMO_34',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	34),
			('ICON_PROMOTION_EXTRA_PROMO_35',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	35),
			('ICON_PROMOTION_EXTRA_PROMO_36',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	36),
			('ICON_PROMOTION_EXTRA_PROMO_37',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	37),
			('ICON_PROMOTION_EXTRA_PROMO_38',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	38),
			('ICON_PROMOTION_EXTRA_PROMO_39',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	39),
			('ICON_PROMOTION_EXTRA_PROMO_40',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	40),
			('ICON_PROMOTION_EXTRA_PROMO_41',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	41),
			('ICON_PROMOTION_EXTRA_PROMO_42',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	42),
			('ICON_PROMOTION_EXTRA_PROMO_43',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	43),
			('ICON_PROMOTION_EXTRA_PROMO_44',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	44),
			('ICON_PROMOTION_EXTRA_PROMO_45',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	45),
			('ICON_PROMOTION_EXTRA_PROMO_46',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	46),
			('ICON_PROMOTION_EXTRA_PROMO_47',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	47),
			('ICON_PROMOTION_EXTRA_PROMO_48',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	48),
			('ICON_PROMOTION_EXTRA_PROMO_49',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	49),
			('ICON_PROMOTION_EXTRA_PROMO_50',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	50),
			('ICON_PROMOTION_EXTRA_PROMO_51',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	51),
			('ICON_PROMOTION_EXTRA_PROMO_52',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	52),
			('ICON_PROMOTION_EXTRA_PROMO_53',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	53),
			('ICON_PROMOTION_EXTRA_PROMO_54',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	54),
			('ICON_PROMOTION_EXTRA_PROMO_55',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	55),
			('ICON_PROMOTION_EXTRA_PROMO_56',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	56),
			('ICON_PROMOTION_EXTRA_PROMO_57',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	57),
			('ICON_PROMOTION_EXTRA_PROMO_58',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	58),
			('ICON_PROMOTION_EXTRA_PROMO_59',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	59),
			('ICON_PROMOTION_EXTRA_PROMO_60',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	60),
			('ICON_PROMOTION_EXTRA_PROMO_61',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	61),
			('ICON_PROMOTION_EXTRA_PROMO_62',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	62),
			('ICON_PROMOTION_EXTRA_PROMO_63',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	63),
			('ICON_PROMOTION_EXTRA_PROMO_64',		'ICON_FONT_TEXTURE_EXTRA_PROMO', 	64),

			('ICON_PROMOTION_PROMO_VP_00_01',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	1),
			('ICON_PROMOTION_PROMO_VP_00_02',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	2),
			('ICON_PROMOTION_PROMO_VP_00_03',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	3),
			('ICON_PROMOTION_PROMO_VP_00_04',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	4),
			('ICON_PROMOTION_PROMO_VP_00_05',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	5),
			('ICON_PROMOTION_PROMO_VP_00_06',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	6),
			('ICON_PROMOTION_PROMO_VP_00_07',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	7),
			('ICON_PROMOTION_PROMO_VP_00_08',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	8),
			('ICON_PROMOTION_PROMO_VP_00_09',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	9),
			('ICON_PROMOTION_PROMO_VP_00_10',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	10),
			('ICON_PROMOTION_PROMO_VP_00_11',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	11),
			('ICON_PROMOTION_PROMO_VP_00_12',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	12),
			('ICON_PROMOTION_PROMO_VP_00_13',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	13),
			('ICON_PROMOTION_PROMO_VP_00_14',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	14),
			('ICON_PROMOTION_PROMO_VP_00_15',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	15),
			('ICON_PROMOTION_PROMO_VP_00_16',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	16),
			('ICON_PROMOTION_PROMO_VP_00_17',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	17),
			('ICON_PROMOTION_PROMO_VP_00_18',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	18),
			('ICON_PROMOTION_PROMO_VP_00_19',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	19),
			('ICON_PROMOTION_PROMO_VP_00_20',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	20),
			('ICON_PROMOTION_PROMO_VP_00_21',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	21),
			('ICON_PROMOTION_PROMO_VP_00_22',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	22),
			('ICON_PROMOTION_PROMO_VP_00_23',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	23),
			('ICON_PROMOTION_PROMO_VP_00_24',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	24),
			('ICON_PROMOTION_PROMO_VP_00_25',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	25),
			('ICON_PROMOTION_PROMO_VP_00_26',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	26),
			('ICON_PROMOTION_PROMO_VP_00_27',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	27),
			('ICON_PROMOTION_PROMO_VP_00_28',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	28),
			('ICON_PROMOTION_PROMO_VP_00_29',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	29),
			('ICON_PROMOTION_PROMO_VP_00_30',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	30),
			('ICON_PROMOTION_PROMO_VP_00_31',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	31),
			('ICON_PROMOTION_PROMO_VP_00_32',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	70),
			('ICON_PROMOTION_PROMO_VP_00_33',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	33),
			('ICON_PROMOTION_PROMO_VP_00_34',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	34),
			('ICON_PROMOTION_PROMO_VP_00_35',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	35),
			('ICON_PROMOTION_PROMO_VP_00_36',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	36),
			('ICON_PROMOTION_PROMO_VP_00_37',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	37),
			('ICON_PROMOTION_PROMO_VP_00_38',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	38),
			('ICON_PROMOTION_PROMO_VP_00_39',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	39),
			('ICON_PROMOTION_PROMO_VP_00_40',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	40),
			('ICON_PROMOTION_PROMO_VP_00_41',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	41),
			('ICON_PROMOTION_PROMO_VP_00_42',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	42),
			('ICON_PROMOTION_PROMO_VP_00_43',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	43),
			('ICON_PROMOTION_PROMO_VP_00_44',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	44),
			('ICON_PROMOTION_PROMO_VP_00_45',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	45),
			('ICON_PROMOTION_PROMO_VP_00_46',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	46),
			('ICON_PROMOTION_PROMO_VP_00_47',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	47),
			('ICON_PROMOTION_PROMO_VP_00_48',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	48),
			('ICON_PROMOTION_PROMO_VP_00_49',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	49),
			('ICON_PROMOTION_PROMO_VP_00_50',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	50),
			('ICON_PROMOTION_PROMO_VP_00_51',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	51),
			('ICON_PROMOTION_PROMO_VP_00_52',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	52),
			('ICON_PROMOTION_PROMO_VP_00_53',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	53),
			('ICON_PROMOTION_PROMO_VP_00_54',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	54),
			('ICON_PROMOTION_PROMO_VP_00_55',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	55),
			('ICON_PROMOTION_PROMO_VP_00_56',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	56),
			('ICON_PROMOTION_PROMO_VP_00_57',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	57),
			('ICON_PROMOTION_PROMO_VP_00_58',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	58),
			('ICON_PROMOTION_PROMO_VP_00_59',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	59),
			('ICON_PROMOTION_PROMO_VP_00_60',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	60),
			('ICON_PROMOTION_PROMO_VP_00_61',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	61),
			('ICON_PROMOTION_PROMO_VP_00_62',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	62),
			('ICON_PROMOTION_PROMO_VP_00_63',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	63),
			('ICON_PROMOTION_PROMO_VP_00_64',		'ICON_FONT_TEXTURE_PROMO_VP_00', 	64),

			('ICON_PROMOTION_PROMO_VP_01_01',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	1),
			('ICON_PROMOTION_PROMO_VP_01_02',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	2),
			('ICON_PROMOTION_PROMO_VP_01_03',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	3),
			('ICON_PROMOTION_PROMO_VP_01_04',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	4),
			('ICON_PROMOTION_PROMO_VP_01_05',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	5),
			('ICON_PROMOTION_PROMO_VP_01_06',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	6),
			('ICON_PROMOTION_PROMO_VP_01_07',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	7),
			('ICON_PROMOTION_PROMO_VP_01_08',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	8),
			('ICON_PROMOTION_PROMO_VP_01_09',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	9),
			('ICON_PROMOTION_PROMO_VP_01_10',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	10),
			('ICON_PROMOTION_PROMO_VP_01_11',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	11),
			('ICON_PROMOTION_PROMO_VP_01_12',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	12),
			('ICON_PROMOTION_PROMO_VP_01_13',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	13),
			('ICON_PROMOTION_PROMO_VP_01_14',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	14),
			('ICON_PROMOTION_PROMO_VP_01_15',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	15),
			('ICON_PROMOTION_PROMO_VP_01_16',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	16),
			('ICON_PROMOTION_PROMO_VP_01_17',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	17),
			('ICON_PROMOTION_PROMO_VP_01_18',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	18),
			('ICON_PROMOTION_PROMO_VP_01_19',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	19),
			('ICON_PROMOTION_PROMO_VP_01_20',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	20),
			('ICON_PROMOTION_PROMO_VP_01_21',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	21),
			('ICON_PROMOTION_PROMO_VP_01_22',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	22),
			('ICON_PROMOTION_PROMO_VP_01_23',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	23),
			('ICON_PROMOTION_PROMO_VP_01_24',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	24),
			('ICON_PROMOTION_PROMO_VP_01_25',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	25),
			('ICON_PROMOTION_PROMO_VP_01_26',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	26),
			('ICON_PROMOTION_PROMO_VP_01_27',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	27),
			('ICON_PROMOTION_PROMO_VP_01_28',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	28),
			('ICON_PROMOTION_PROMO_VP_01_29',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	29),
			('ICON_PROMOTION_PROMO_VP_01_30',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	30),
			('ICON_PROMOTION_PROMO_VP_01_31',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	31),
			('ICON_PROMOTION_PROMO_VP_01_32',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	70),
			('ICON_PROMOTION_PROMO_VP_01_33',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	33),
			('ICON_PROMOTION_PROMO_VP_01_34',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	34),
			('ICON_PROMOTION_PROMO_VP_01_35',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	35),
			('ICON_PROMOTION_PROMO_VP_01_36',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	36),
			('ICON_PROMOTION_PROMO_VP_01_37',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	37),
			('ICON_PROMOTION_PROMO_VP_01_38',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	38),
			('ICON_PROMOTION_PROMO_VP_01_39',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	39),
			('ICON_PROMOTION_PROMO_VP_01_40',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	40),
			('ICON_PROMOTION_PROMO_VP_01_41',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	41),
			('ICON_PROMOTION_PROMO_VP_01_42',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	42),
			('ICON_PROMOTION_PROMO_VP_01_43',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	43),
			('ICON_PROMOTION_PROMO_VP_01_44',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	44),
			('ICON_PROMOTION_PROMO_VP_01_45',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	45),
			('ICON_PROMOTION_PROMO_VP_01_46',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	46),
			('ICON_PROMOTION_PROMO_VP_01_47',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	47),
			('ICON_PROMOTION_PROMO_VP_01_48',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	48),
			('ICON_PROMOTION_PROMO_VP_01_49',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	49),
			('ICON_PROMOTION_PROMO_VP_01_50',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	50),
			('ICON_PROMOTION_PROMO_VP_01_51',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	51),
			('ICON_PROMOTION_PROMO_VP_01_52',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	52),
			('ICON_PROMOTION_PROMO_VP_01_53',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	53),
			('ICON_PROMOTION_PROMO_VP_01_54',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	54),
			('ICON_PROMOTION_PROMO_VP_01_55',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	55),
			('ICON_PROMOTION_PROMO_VP_01_56',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	56),
			('ICON_PROMOTION_PROMO_VP_01_57',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	57),
			('ICON_PROMOTION_PROMO_VP_01_58',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	58),
			('ICON_PROMOTION_PROMO_VP_01_59',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	59),
			('ICON_PROMOTION_PROMO_VP_01_60',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	60),
			('ICON_PROMOTION_PROMO_VP_01_61',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	61),
			('ICON_PROMOTION_PROMO_VP_01_62',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	62),
			('ICON_PROMOTION_PROMO_VP_01_63',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	63),
			('ICON_PROMOTION_PROMO_VP_01_64',		'ICON_FONT_TEXTURE_PROMO_VP_01', 	64),

			('ICON_PROMOTION_PROMO_VP_02_01',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	1),
			('ICON_PROMOTION_PROMO_VP_02_02',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	2),
			('ICON_PROMOTION_PROMO_VP_02_03',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	3),
			('ICON_PROMOTION_PROMO_VP_02_04',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	4),
			('ICON_PROMOTION_PROMO_VP_02_05',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	5),
			('ICON_PROMOTION_PROMO_VP_02_06',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	6),
			('ICON_PROMOTION_PROMO_VP_02_07',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	7),
			('ICON_PROMOTION_PROMO_VP_02_08',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	8),
			('ICON_PROMOTION_PROMO_VP_02_09',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	9),
			('ICON_PROMOTION_PROMO_VP_02_10',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	10),
			('ICON_PROMOTION_PROMO_VP_02_11',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	11),
			('ICON_PROMOTION_PROMO_VP_02_12',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	12),
			('ICON_PROMOTION_PROMO_VP_02_13',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	13),
			('ICON_PROMOTION_PROMO_VP_02_14',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	14),
			('ICON_PROMOTION_PROMO_VP_02_15',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	15),
			('ICON_PROMOTION_PROMO_VP_02_16',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	16),
			('ICON_PROMOTION_PROMO_VP_02_17',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	17),
			('ICON_PROMOTION_PROMO_VP_02_18',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	18),
			('ICON_PROMOTION_PROMO_VP_02_19',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	19),
			('ICON_PROMOTION_PROMO_VP_02_20',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	20),
			('ICON_PROMOTION_PROMO_VP_02_21',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	21),
			('ICON_PROMOTION_PROMO_VP_02_22',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	22),
			('ICON_PROMOTION_PROMO_VP_02_23',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	23),
			('ICON_PROMOTION_PROMO_VP_02_24',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	24),
			('ICON_PROMOTION_PROMO_VP_02_25',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	25),
			('ICON_PROMOTION_PROMO_VP_02_26',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	26),
			('ICON_PROMOTION_PROMO_VP_02_27',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	27),
			('ICON_PROMOTION_PROMO_VP_02_28',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	28),
			('ICON_PROMOTION_PROMO_VP_02_29',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	29),
			('ICON_PROMOTION_PROMO_VP_02_30',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	30),
			('ICON_PROMOTION_PROMO_VP_02_31',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	31),
			('ICON_PROMOTION_PROMO_VP_02_32',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	70),
			('ICON_PROMOTION_PROMO_VP_02_33',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	33),
			('ICON_PROMOTION_PROMO_VP_02_34',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	34),
			('ICON_PROMOTION_PROMO_VP_02_35',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	35),
			('ICON_PROMOTION_PROMO_VP_02_36',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	36),
			('ICON_PROMOTION_PROMO_VP_02_37',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	37),
			('ICON_PROMOTION_PROMO_VP_02_38',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	38),
			('ICON_PROMOTION_PROMO_VP_02_39',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	39),
			('ICON_PROMOTION_PROMO_VP_02_40',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	40),
			('ICON_PROMOTION_PROMO_VP_02_41',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	41),
			('ICON_PROMOTION_PROMO_VP_02_42',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	42),
			('ICON_PROMOTION_PROMO_VP_02_43',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	43),
			('ICON_PROMOTION_PROMO_VP_02_44',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	44),
			('ICON_PROMOTION_PROMO_VP_02_45',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	45),
			('ICON_PROMOTION_PROMO_VP_02_46',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	46),
			('ICON_PROMOTION_PROMO_VP_02_47',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	47),
			('ICON_PROMOTION_PROMO_VP_02_48',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	48),
			('ICON_PROMOTION_PROMO_VP_02_49',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	49),
			('ICON_PROMOTION_PROMO_VP_02_50',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	50),
			('ICON_PROMOTION_PROMO_VP_02_51',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	51),
			('ICON_PROMOTION_PROMO_VP_02_52',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	52),
			('ICON_PROMOTION_PROMO_VP_02_53',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	53),
			('ICON_PROMOTION_PROMO_VP_02_54',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	54),
			('ICON_PROMOTION_PROMO_VP_02_55',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	55),
			('ICON_PROMOTION_PROMO_VP_02_56',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	56),
			('ICON_PROMOTION_PROMO_VP_02_57',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	57),
			('ICON_PROMOTION_PROMO_VP_02_58',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	58),
			('ICON_PROMOTION_PROMO_VP_02_59',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	59),
			('ICON_PROMOTION_PROMO_VP_02_60',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	60),
			('ICON_PROMOTION_PROMO_VP_02_61',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	61),
			('ICON_PROMOTION_PROMO_VP_02_62',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	62),
			('ICON_PROMOTION_PROMO_VP_02_63',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	63),
			('ICON_PROMOTION_PROMO_VP_02_64',		'ICON_FONT_TEXTURE_PROMO_VP_02', 	64),

			('ICON_PROMOTION_PROMO_VP_03_01',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	1),
			('ICON_PROMOTION_PROMO_VP_03_02',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	2),
			('ICON_PROMOTION_PROMO_VP_03_03',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	3),
			('ICON_PROMOTION_PROMO_VP_03_04',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	4),
			('ICON_PROMOTION_PROMO_VP_03_05',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	5),
			('ICON_PROMOTION_PROMO_VP_03_06',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	6),
			('ICON_PROMOTION_PROMO_VP_03_07',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	7),
			('ICON_PROMOTION_PROMO_VP_03_08',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	8),
			('ICON_PROMOTION_PROMO_VP_03_09',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	9),
			('ICON_PROMOTION_PROMO_VP_03_10',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	10),
			('ICON_PROMOTION_PROMO_VP_03_11',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	11),
			('ICON_PROMOTION_PROMO_VP_03_12',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	12),
			('ICON_PROMOTION_PROMO_VP_03_13',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	13),
			('ICON_PROMOTION_PROMO_VP_03_14',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	14),
			('ICON_PROMOTION_PROMO_VP_03_15',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	15),
			('ICON_PROMOTION_PROMO_VP_03_16',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	16),
			('ICON_PROMOTION_PROMO_VP_03_17',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	17),
			('ICON_PROMOTION_PROMO_VP_03_18',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	18),
			('ICON_PROMOTION_PROMO_VP_03_19',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	19),
			('ICON_PROMOTION_PROMO_VP_03_20',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	20),
			('ICON_PROMOTION_PROMO_VP_03_21',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	21),
			('ICON_PROMOTION_PROMO_VP_03_22',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	22),
			('ICON_PROMOTION_PROMO_VP_03_23',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	23),
			('ICON_PROMOTION_PROMO_VP_03_24',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	24),
			('ICON_PROMOTION_PROMO_VP_03_25',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	25),
			('ICON_PROMOTION_PROMO_VP_03_26',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	26),
			('ICON_PROMOTION_PROMO_VP_03_27',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	27),
			('ICON_PROMOTION_PROMO_VP_03_28',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	28),
			('ICON_PROMOTION_PROMO_VP_03_29',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	29),
			('ICON_PROMOTION_PROMO_VP_03_30',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	30),
			('ICON_PROMOTION_PROMO_VP_03_31',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	31),
			('ICON_PROMOTION_PROMO_VP_03_32',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	70),
			('ICON_PROMOTION_PROMO_VP_03_33',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	33),
			('ICON_PROMOTION_PROMO_VP_03_34',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	34),
			('ICON_PROMOTION_PROMO_VP_03_35',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	35),
			('ICON_PROMOTION_PROMO_VP_03_36',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	36),
			('ICON_PROMOTION_PROMO_VP_03_37',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	37),
			('ICON_PROMOTION_PROMO_VP_03_38',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	38),
			('ICON_PROMOTION_PROMO_VP_03_39',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	39),
			('ICON_PROMOTION_PROMO_VP_03_40',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	40),
			('ICON_PROMOTION_PROMO_VP_03_41',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	41),
			('ICON_PROMOTION_PROMO_VP_03_42',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	42),
			('ICON_PROMOTION_PROMO_VP_03_43',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	43),
			('ICON_PROMOTION_PROMO_VP_03_44',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	44),
			('ICON_PROMOTION_PROMO_VP_03_45',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	45),
			('ICON_PROMOTION_PROMO_VP_03_46',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	46),
			('ICON_PROMOTION_PROMO_VP_03_47',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	47),
			('ICON_PROMOTION_PROMO_VP_03_48',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	48),
			('ICON_PROMOTION_PROMO_VP_03_49',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	49),
			('ICON_PROMOTION_PROMO_VP_03_50',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	50),
			('ICON_PROMOTION_PROMO_VP_03_51',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	51),
			('ICON_PROMOTION_PROMO_VP_03_52',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	52),
			('ICON_PROMOTION_PROMO_VP_03_53',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	53),
			('ICON_PROMOTION_PROMO_VP_03_54',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	54),
			('ICON_PROMOTION_PROMO_VP_03_55',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	55),
			('ICON_PROMOTION_PROMO_VP_03_56',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	56),
			('ICON_PROMOTION_PROMO_VP_03_57',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	57),
			('ICON_PROMOTION_PROMO_VP_03_58',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	58),
			('ICON_PROMOTION_PROMO_VP_03_59',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	59),
			('ICON_PROMOTION_PROMO_VP_03_60',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	60),
			('ICON_PROMOTION_PROMO_VP_03_61',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	61),
			('ICON_PROMOTION_PROMO_VP_03_62',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	62),
			('ICON_PROMOTION_PROMO_VP_03_63',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	63),
			('ICON_PROMOTION_PROMO_VP_03_64',		'ICON_FONT_TEXTURE_PROMO_VP_03', 	64),

			('ICON_PROMOTION_PROMO_FANTASY_01',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	1),
			('ICON_PROMOTION_PROMO_FANTASY_02',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	2),
			('ICON_PROMOTION_PROMO_FANTASY_03',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	3),
			('ICON_PROMOTION_PROMO_FANTASY_04',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	4),
			('ICON_PROMOTION_PROMO_FANTASY_05',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	5),
			('ICON_PROMOTION_PROMO_FANTASY_06',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	6),
			('ICON_PROMOTION_PROMO_FANTASY_07',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	7),
			('ICON_PROMOTION_PROMO_FANTASY_08',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	8),
			('ICON_PROMOTION_PROMO_FANTASY_09',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	9),
			('ICON_PROMOTION_PROMO_FANTASY_10',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	10),
			('ICON_PROMOTION_PROMO_FANTASY_11',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	11),
			('ICON_PROMOTION_PROMO_FANTASY_12',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	12),
			('ICON_PROMOTION_PROMO_FANTASY_13',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	13),
			('ICON_PROMOTION_PROMO_FANTASY_14',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	14),
			('ICON_PROMOTION_PROMO_FANTASY_15',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	15),
			('ICON_PROMOTION_PROMO_FANTASY_16',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	16),
			('ICON_PROMOTION_PROMO_FANTASY_17',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	17),
			('ICON_PROMOTION_PROMO_FANTASY_18',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	18),
			('ICON_PROMOTION_PROMO_FANTASY_19',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	19),
			('ICON_PROMOTION_PROMO_FANTASY_20',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	20),
			('ICON_PROMOTION_PROMO_FANTASY_21',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	21),
			('ICON_PROMOTION_PROMO_FANTASY_22',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	22),
			('ICON_PROMOTION_PROMO_FANTASY_23',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	23),
			('ICON_PROMOTION_PROMO_FANTASY_24',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	24),
			('ICON_PROMOTION_PROMO_FANTASY_25',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	25),
			('ICON_PROMOTION_PROMO_FANTASY_26',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	26),
			('ICON_PROMOTION_PROMO_FANTASY_27',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	27),
			('ICON_PROMOTION_PROMO_FANTASY_28',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	28),
			('ICON_PROMOTION_PROMO_FANTASY_29',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	29),
			('ICON_PROMOTION_PROMO_FANTASY_30',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	30),
			('ICON_PROMOTION_PROMO_FANTASY_31',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	31),
			('ICON_PROMOTION_PROMO_FANTASY_32',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	70),
			('ICON_PROMOTION_PROMO_FANTASY_33',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	33),
			('ICON_PROMOTION_PROMO_FANTASY_34',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	34),
			('ICON_PROMOTION_PROMO_FANTASY_35',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	35),
			('ICON_PROMOTION_PROMO_FANTASY_36',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	36),
			('ICON_PROMOTION_PROMO_FANTASY_37',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	37),
			('ICON_PROMOTION_PROMO_FANTASY_38',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	38),
			('ICON_PROMOTION_PROMO_FANTASY_39',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	39),
			('ICON_PROMOTION_PROMO_FANTASY_40',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	40),
			('ICON_PROMOTION_PROMO_FANTASY_41',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	41),
			('ICON_PROMOTION_PROMO_FANTASY_42',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	42),
			('ICON_PROMOTION_PROMO_FANTASY_43',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	43),
			('ICON_PROMOTION_PROMO_FANTASY_44',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	44),
			('ICON_PROMOTION_PROMO_FANTASY_45',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	45),
			('ICON_PROMOTION_PROMO_FANTASY_46',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	46),
			('ICON_PROMOTION_PROMO_FANTASY_47',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	47),
			('ICON_PROMOTION_PROMO_FANTASY_48',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	48),
			('ICON_PROMOTION_PROMO_FANTASY_49',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	49),
			('ICON_PROMOTION_PROMO_FANTASY_50',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	50),
			('ICON_PROMOTION_PROMO_FANTASY_51',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	51),
			('ICON_PROMOTION_PROMO_FANTASY_52',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	52),
			('ICON_PROMOTION_PROMO_FANTASY_53',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	53),
			('ICON_PROMOTION_PROMO_FANTASY_54',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	54),
			('ICON_PROMOTION_PROMO_FANTASY_55',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	55),
			('ICON_PROMOTION_PROMO_FANTASY_56',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	56),
			('ICON_PROMOTION_PROMO_FANTASY_57',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	57),
			('ICON_PROMOTION_PROMO_FANTASY_58',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	58),
			('ICON_PROMOTION_PROMO_FANTASY_59',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	59),
			('ICON_PROMOTION_PROMO_FANTASY_60',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	60),
			('ICON_PROMOTION_PROMO_FANTASY_61',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	61),
			('ICON_PROMOTION_PROMO_FANTASY_62',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	62),
			('ICON_PROMOTION_PROMO_FANTASY_63',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	63),
			('ICON_PROMOTION_PROMO_FANTASY_64',		'ICON_FONT_TEXTURE_PROMO_FANTASY', 	64),

			('ICON_PROMOTION_TEMP_VPPI_01',			'ICON_FONT_TEXTURE_TEMP_VPPI', 		1),
			('ICON_PROMOTION_TEMP_VPPI_02',			'ICON_FONT_TEXTURE_TEMP_VPPI', 		2),
			('ICON_PROMOTION_TEMP_VPPI_03',			'ICON_FONT_TEXTURE_TEMP_VPPI', 		3),
			('ICON_PROMOTION_TEMP_VPPI_04',			'ICON_FONT_TEXTURE_TEMP_VPPI', 		4),
			('ICON_PROMOTION_TEMP_VPPI_05',			'ICON_FONT_TEXTURE_TEMP_VPPI', 		5),
			('ICON_PROMOTION_TEMP_VPPI_06',			'ICON_FONT_TEXTURE_TEMP_VPPI', 		6),
			('ICON_PROMOTION_TEMP_VPPI_07',			'ICON_FONT_TEXTURE_TEMP_VPPI', 		7),
			('ICON_PROMOTION_TEMP_VPPI_08',			'ICON_FONT_TEXTURE_TEMP_VPPI', 		8),
			('ICON_PROMOTION_TEMP_VPPI_09',			'ICON_FONT_TEXTURE_TEMP_VPPI', 		9),
			('ICON_PROMOTION_TEMP_VPPI_10',			'ICON_FONT_TEXTURE_TEMP_VPPI', 		10),
			('ICON_PROMOTION_TEMP_VPPI_11',			'ICON_FONT_TEXTURE_TEMP_VPPI', 		11),
			('ICON_PROMOTION_TEMP_VPPI_12',			'ICON_FONT_TEXTURE_TEMP_VPPI', 		12),
			('ICON_PROMOTION_TEMP_VPPI_13',			'ICON_FONT_TEXTURE_TEMP_VPPI', 		13),
			('ICON_PROMOTION_TEMP_VPPI_14',			'ICON_FONT_TEXTURE_TEMP_VPPI', 		14),
			('ICON_PROMOTION_TEMP_VPPI_15',			'ICON_FONT_TEXTURE_TEMP_VPPI', 		15),
			('ICON_PROMOTION_TEMP_VPPI_16',			'ICON_FONT_TEXTURE_TEMP_VPPI', 		16),

			('ICON_PROMOTION_CPM_TNL',				'ICON_FONT_TEXTURE_CPM_TNL', 		1),
			('ICON_PROMOTION_FIRESHIP_TNL',			'ICON_FONT_TEXTURE_FIRESHIP_TNL', 	1),
			('ICON_PROMOTION_YFS_SEA',				'ICON_FONT_TEXTURE_YFS_SEA', 		1);

UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_01]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 0;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_02]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 1;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_03]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 2;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_04]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 3;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_05]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 4;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_06]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 5;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_07]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 6;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_08]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 7;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_09]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 8;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_10]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 9;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_11]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 10;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_12]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 11;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_13]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 12;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_14]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 13;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_15]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 14;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_16]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 15;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_17]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 16;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_18]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 17;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_19]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 18;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_20]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 19;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_21]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 20;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_22]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 21;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_23]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 22;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_24]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 23;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_25]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 24;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_26]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 25;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_27]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 26;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_28]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 27;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_29]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 28;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_30]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 29;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_31]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 30;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_32]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 31;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_33]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 32;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_34]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 33;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_35]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 34;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_36]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 35;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_37]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 36;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_38]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 37;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_39]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 38;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_40]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 39;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_41]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 40;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_42]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 41;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_43]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 42;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_44]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 43;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_45]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 44;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_46]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 45;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_47]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 46;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_48]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 47;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_49]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 48;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_50]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 49;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_51]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 50;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_52]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 51;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_53]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 52;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_54]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 53;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_55]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 54;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_56]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 55;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_57]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 56;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_58]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 57;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_59]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 58;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_60]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 59;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_61]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 60;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_62]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 61;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_63]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 62;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_64]'	WHERE IconAtlas = 'extraPromo_Atlas'	AND PortraitIndex = 63;
			
			
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_01]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 0;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_02]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 1;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_03]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 2;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_04]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 3;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_05]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 4;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_06]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 5;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_07]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 6;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_08]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 7;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_09]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 8;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_10]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 9;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_11]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 10;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_12]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 11;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_13]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 12;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_14]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 13;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_15]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 14;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_16]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 15;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_17]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 16;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_18]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 17;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_19]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 18;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_20]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 19;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_21]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 20;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_22]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 21;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_23]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 22;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_24]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 23;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_25]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 24;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_26]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 25;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_27]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 26;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_28]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 27;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_29]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 28;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_30]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 29;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_31]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 30;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_32]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 31;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_33]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 32;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_34]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 33;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_35]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 34;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_36]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 35;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_37]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 36;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_38]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 37;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_39]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 38;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_40]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 39;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_41]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 40;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_42]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 41;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_43]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 42;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_44]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 43;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_45]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 44;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_46]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 45;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_47]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 46;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_48]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 47;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_49]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 48;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_50]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 49;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_51]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 50;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_52]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 51;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_53]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 52;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_54]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 53;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_55]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 54;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_56]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 55;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_57]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 56;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_58]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 57;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_59]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 58;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_60]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 59;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_61]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 60;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_62]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 61;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_63]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 62;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_00_64]'	WHERE IconAtlas = 'promoVP_atlas_00'	AND PortraitIndex = 63;
			
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_01]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 0;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_02]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 1;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_03]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 2;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_04]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 3;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_05]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 4;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_06]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 5;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_07]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 6;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_08]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 7;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_09]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 8;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_10]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 9;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_11]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 10;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_12]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 11;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_13]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 12;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_14]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 13;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_15]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 14;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_16]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 15;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_17]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 16;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_18]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 17;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_19]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 18;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_20]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 19;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_21]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 20;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_22]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 21;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_23]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 22;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_24]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 23;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_25]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 24;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_26]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 25;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_27]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 26;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_28]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 27;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_29]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 28;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_30]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 29;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_31]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 30;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_32]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 31;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_33]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 32;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_34]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 33;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_35]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 34;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_36]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 35;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_37]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 36;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_38]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 37;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_39]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 38;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_40]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 39;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_41]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 40;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_42]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 41;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_43]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 42;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_44]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 43;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_45]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 44;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_46]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 45;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_47]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 46;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_48]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 47;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_49]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 48;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_50]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 49;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_51]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 50;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_52]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 51;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_53]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 52;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_54]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 53;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_55]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 54;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_56]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 55;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_57]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 56;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_58]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 57;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_59]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 58;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_60]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 59;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_61]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 60;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_62]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 61;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_63]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 62;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_64]'	WHERE IconAtlas = 'promoVP_atlas_01'	AND PortraitIndex = 63;
			
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_01]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 0;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_02]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 1;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_03]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 2;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_04]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 3;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_05]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 4;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_06]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 5;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_07]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 6;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_08]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 7;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_09]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 8;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_10]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 9;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_11]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 10;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_12]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 11;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_13]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 12;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_14]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 13;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_15]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 14;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_16]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 15;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_17]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 16;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_18]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 17;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_19]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 18;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_20]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 19;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_21]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 20;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_22]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 21;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_23]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 22;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_24]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 23;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_25]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 24;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_26]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 25;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_27]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 26;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_28]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 27;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_29]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 28;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_30]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 29;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_31]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 30;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_32]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 31;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_33]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 32;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_34]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 33;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_35]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 34;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_36]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 35;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_37]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 36;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_38]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 37;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_39]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 38;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_40]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 39;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_41]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 40;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_42]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 41;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_43]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 42;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_44]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 43;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_45]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 44;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_46]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 45;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_47]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 46;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_48]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 47;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_49]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 48;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_50]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 49;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_51]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 50;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_52]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 51;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_53]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 52;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_54]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 53;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_55]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 54;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_56]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 55;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_57]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 56;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_58]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 57;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_59]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 58;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_60]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 59;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_61]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 60;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_62]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 61;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_63]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 62;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_02_64]'	WHERE IconAtlas = 'promoVP_atlas_02'	AND PortraitIndex = 63;
			
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_01]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 0;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_02]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 1;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_03]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 2;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_04]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 3;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_05]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 4;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_06]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 5;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_07]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 6;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_08]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 7;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_09]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 8;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_10]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 9;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_11]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 10;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_12]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 11;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_13]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 12;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_14]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 13;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_15]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 14;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_16]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 15;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_17]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 16;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_18]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 17;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_19]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 18;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_20]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 19;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_21]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 20;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_22]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 21;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_23]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 22;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_24]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 23;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_25]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 24;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_26]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 25;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_27]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 26;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_28]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 27;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_29]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 28;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_30]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 29;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_31]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 30;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_32]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 31;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_33]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 32;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_34]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 33;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_35]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 34;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_36]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 35;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_37]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 36;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_38]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 37;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_39]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 38;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_40]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 39;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_41]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 40;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_42]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 41;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_43]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 42;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_44]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 43;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_45]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 44;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_46]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 45;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_47]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 46;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_48]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 47;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_49]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 48;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_50]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 49;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_51]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 50;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_52]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 51;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_53]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 52;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_54]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 53;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_55]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 54;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_56]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 55;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_57]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 56;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_58]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 57;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_59]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 58;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_60]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 59;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_61]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 60;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_62]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 61;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_63]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 62;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_64]'	WHERE IconAtlas = 'promoVP_atlas_03'	AND PortraitIndex = 63;
			
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_01]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 0;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_02]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 1;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_03]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 2;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_04]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 3;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_05]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 4;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_06]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 5;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_07]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 6;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_08]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 7;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_09]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 8;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_10]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 9;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_11]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 10;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_12]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 11;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_13]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 12;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_14]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 13;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_15]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 14;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_16]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 15;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_17]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 16;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_18]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 17;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_19]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 18;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_20]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 19;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_21]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 20;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_22]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 21;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_23]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 22;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_24]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 23;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_25]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 24;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_26]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 25;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_27]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 26;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_28]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 27;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_29]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 28;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_30]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 29;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_31]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 30;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_32]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 31;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_33]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 32;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_34]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 33;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_35]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 34;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_36]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 35;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_37]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 36;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_38]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 37;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_39]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 38;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_40]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 39;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_41]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 40;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_42]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 41;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_43]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 42;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_44]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 43;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_45]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 44;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_46]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 45;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_47]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 46;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_48]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 47;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_49]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 48;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_50]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 49;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_51]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 50;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_52]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 51;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_53]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 52;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_54]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 53;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_55]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 54;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_56]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 55;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_57]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 56;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_58]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 57;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_59]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 58;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_60]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 59;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_61]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 60;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_62]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 61;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_63]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 62;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_FANTASY_64]'	WHERE (IconAtlas = 'Blood_Flag_ATLAS' OR IconAtlas = 'EX_PROMOTION_A_ATLAS')	AND PortraitIndex = 63;
			
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_TEMP_VPPI_01]'	WHERE IconAtlas = 'tempVPPI_Atlas'	AND PortraitIndex = 0;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_TEMP_VPPI_02]'	WHERE IconAtlas = 'tempVPPI_Atlas'	AND PortraitIndex = 1;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_TEMP_VPPI_03]'	WHERE IconAtlas = 'tempVPPI_Atlas'	AND PortraitIndex = 2;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_TEMP_VPPI_04]'	WHERE IconAtlas = 'tempVPPI_Atlas'	AND PortraitIndex = 3;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_TEMP_VPPI_05]'	WHERE IconAtlas = 'tempVPPI_Atlas'	AND PortraitIndex = 4;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_TEMP_VPPI_06]'	WHERE IconAtlas = 'tempVPPI_Atlas'	AND PortraitIndex = 5;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_TEMP_VPPI_07]'	WHERE IconAtlas = 'tempVPPI_Atlas'	AND PortraitIndex = 6;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_TEMP_VPPI_08]'	WHERE IconAtlas = 'tempVPPI_Atlas'	AND PortraitIndex = 7;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_TEMP_VPPI_09]'	WHERE IconAtlas = 'tempVPPI_Atlas'	AND PortraitIndex = 8;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_TEMP_VPPI_10]'	WHERE IconAtlas = 'tempVPPI_Atlas'	AND PortraitIndex = 9;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_TEMP_VPPI_11]'	WHERE IconAtlas = 'tempVPPI_Atlas'	AND PortraitIndex = 10;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_TEMP_VPPI_12]'	WHERE IconAtlas = 'tempVPPI_Atlas'	AND PortraitIndex = 11;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_TEMP_VPPI_13]'	WHERE IconAtlas = 'tempVPPI_Atlas'	AND PortraitIndex = 12;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_TEMP_VPPI_14]'	WHERE IconAtlas = 'tempVPPI_Atlas'	AND PortraitIndex = 13;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_TEMP_VPPI_15]'	WHERE IconAtlas = 'tempVPPI_Atlas'	AND PortraitIndex = 14;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_TEMP_VPPI_16]'	WHERE IconAtlas = 'tempVPPI_Atlas'	AND PortraitIndex = 15;


UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_58]'	WHERE IconAtlas = 'ROME_PROMOTION_B_ATLAS'	AND PortraitIndex = 57;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_57]'	WHERE IconAtlas = 'ROME_PROMOTION_B_ATLAS'	AND PortraitIndex = 56;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_12]'	WHERE IconAtlas = 'ROME_PROMOTION_B_ATLAS'	AND PortraitIndex = 11;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_46]'	WHERE IconAtlas = 'ROME_PROMOTION_B_ATLAS'	AND PortraitIndex = 45;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_47]'	WHERE IconAtlas = 'ROME_PROMOTION_B_ATLAS'	AND PortraitIndex = 46;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_59]'	WHERE IconAtlas = 'ROME_PROMOTION_B_ATLAS'	AND PortraitIndex = 58;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_43]'	WHERE IconAtlas = 'ROME_PROMOTION_B_ATLAS'	AND PortraitIndex = 42;

UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_01_30]'	WHERE IconAtlas = 'ROME_PROMOTION_A_ATLAS'	AND PortraitIndex = 29;

UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_10]'	WHERE IconAtlas = 'EX_PROMOTION_C_ATLAS'	AND PortraitIndex = 9;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_PROMO_VP_03_34]'	WHERE IconAtlas = 'EX_PROMOTION_C_ATLAS'	AND PortraitIndex = 33;

UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_05]'	WHERE IconAtlas = 'EX_PROMOTION_B_ATLAS'	AND PortraitIndex = 4;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_22]'	WHERE IconAtlas = 'EX_PROMOTION_B_ATLAS'	AND PortraitIndex = 23;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_EXTRA_PROMO_56]'	WHERE IconAtlas = 'EX_PROMOTION_B_ATLAS'	AND PortraitIndex = 55;


UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_CPM_TNL]'  		WHERE IconAtlas = 'promo_CPM_atlas' 			AND PortraitIndex = 0;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_FIRESHIP_TNL]' 	WHERE IconAtlas = 'FIRESHIP_PROMOTION_ATLAS' 	AND PortraitIndex = 0;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_YFS_SEA]'  		WHERE IconAtlas = 'extraPromo_Atlas' 			AND PortraitIndex = 31;

UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_NEGATIVE_ATTRIBUTES]' WHERE (IconAtlas = 'ABILITY_ATLAS' OR IconAtlas = 'PROMOTION_ATLAS') AND PortraitIndex = 57;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_COASTAL_RAIDER_3]'    WHERE IconAtlas = 'EXPANSION_PROMOTION_ATLAS'  AND PortraitIndex = 5;
UPDATE UnitPromotions SET IconStringSP = '[ICON_PROMOTION_TRADE_MISSION_BONUS]' WHERE IconAtlas = 'EXPANSION2_PROMOTION_ATLAS' AND PortraitIndex = 8;